### ISSUE TITLE
Table.list(db, eid) function is does not works with eid parameter

### ISSUE THREAD

**Issue by dsvalenciah** [odarbelaeze/condor-api#15]
A bug encountered into app.py, please test `Document.list(database, bibliography_eid)`.
I had to do this `for bib in Bibliography.list(db) if bib.eid == bibliography_eid` because `Document.list(database, bibliography_eid)` is not working.

**Comment by odarbelaeze** [comment]
Ah, this is not supposed to work like that, to find a particular item in a table we should use this function, http://home.condor-ir.co/condor.models.html#condor.models.base.AuditableMixing.find_by_eid
