### ISSUE TITLE
Create a POST /matrix to create a term document matrix should receive options and bibliography eid

### ISSUE THREAD

**Issue by odarbelaeze** [odarbelaeze/condor-api#59]

**Comment by msochel** [comment]
For make this endpoint, see [create matrix](https://github.com/odarbelaeze/condor-ir/blob/master/condor/scripts/matrix.py)

**Comment by msochel** [comment]
For make this endpoint, see [create matrix](https://github.com/odarbelaeze/condor-ir/blob/master/condor/scripts/matrix.py)

**Comment by msochel** [comment]
For make this endpoint, see [create matrix](https://github.com/odarbelaeze/condor-ir/blob/master/condor/scripts/matrix.py#L34)
